### ISSUE TITLE
Can't pick black or white

### ISSUE THREAD

**Issue by Jorundur** [croma-app/croma-color-picker#1]
Thanks for a good component, it works well.

However, I think there's a slight limitation in that the user can't pick white or black as their color.

Of course it's possible to just write `#ffffff` for white and `#000000` for black in the text area but it would be nice to be able to pick those colors among the squares.

Perhaps the lightest and darkest square of each palette could be white/black?

E.g. with the default palette (for color `#db0a5b`), the darkest color available is `#330014` and the lightest color available is `#ece4e7`, but perhaps they could be `#ffffff` and `#000000`?

**Comment by kamalkishor1991** [comment]
Hey, 
glad that you liked it. 
The algorithm works by generating shades for each hue of primary colors by varying the saturation, and lightness so for zero saturation the whole row will become black and the same for white. 
I have plans to add more ways of selecting colors so I will try to solve this use-case in some other way.
If you still want to give option to select black and white. Feel free to fork it.
You can change the renderShades to following or just change the topmost to black and bottom right to white by hardcoding in the component.
``` javascript
function renderShades(h) {
    let w = 100, b;
    let colors = [];
    
    for (let i = 0; i < 8; i++) {

        b = 0;
        let rows = [];
        for (let j = 0; j < 10; j++) {
            b = Math.min(100, b);
            w = Math.max(0, w);
            let color = new Color(`hsl(${h},${w},${b})`).tohex();
            rows.push(color);
            b += 11.111111112;
        }
        colors.push(rows);
  
        w -= 14.285714286;
    }
    
    return colors.map((row) => <View style={styles.shadesView}> 
      {row.map((color) => <ColorBox key={color} style={[styles.shadesColorBox]} onPress={() => setSelectedColor(color)} color={color}/>)}
    </View>);
  }
```
Keeping it open for now.

**Comment by kamalkishor1991** [comment]
@Jorundur hey what do you think of PR #3 
![image](https://user-images.githubusercontent.com/5221843/91349453-ece17a80-e802-11ea-89f3-78ad360617f5.png)

**Comment by Jorundur** [comment]
@kamalkishor1991 Looks good! Only thing I'd recommend is sorting the fixed colors list so that the color sequence makes a bit more sense (i.e. the the green colors should be next to each other, etc.)

You could call `.sort()` on the fixed colors list. That way you don't have to worry about the order in the code.

Calling `.sort()` would produce:

```js
["#000000", "#0000ff", "#00ff00", "#00ffa5", "#00ffff", "#ff0000", "#ff00ff", "#ffa500", "#ffff00", "#ffffff"]
```

**Comment by kamalkishor1991** [comment]
Done. 
Thanks for reviewing.

**Comment by kamalkishor1991** [comment]
published new version: 
https://www.npmjs.com/package/croma-color-picker
