### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop

### ISSUE THREAD

**Issue by Jorundur** [croma-app/croma-color-picker#2]
I'm getting a `Warning: Each child in a list should have a unique "key" prop` error when running in my simulator.

This is probably because of the 4 occurrences of `.map` in lines 38-49 that render components without a `key` prop.

Adding the index of the map as a key would probably fix this.

**Comment by kamalkishor1991** [comment]
fixed it now. @Jorundur let me know if you still face the issue. Thanks for reporting it.
